name: weather_app
description: "A Weather app"


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  simple_gradient_text: ^1.3.0
  geolocator:
  http:
  flutter_spinkit:
  permission_handler:
  flutter_svg:
  shared_preferences:
  hive:
  hive_flutter:
  icons_plus: ^5.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter


#  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/conditions/
    - assets/weathericons/
